baseURL = "http://example.org/"
languageCode = "en-us"
title = "Jeril Sebastian"
theme = "yinyang"
googleAnalytics = "UA-96088457-2"

[params]
    headTitle = "Jeril Sebastian"
    mainSections = ["posts"]
    disqus = "jeril-xyz"

    [[params.socials]]
        name = "About Me"
        link = "https://jeril.xyz"

    [[params.socials]]
        name = "Github"
        link = "https://github.com/jerilseb"

[markup]
    [markup.highlight]
        codeFences = true
        guessSyntax = false
        hl_Lines = ""
        lineNoStart = 1
        lineNos = false
        lineNumbersInTable = true
        noClasses = true
        # style = "solarized-dark"
        # style = "perldoc"
        # style = "tango"
        # style = "native"
        style = "dracula"
        tabWidth = 4