baseURL = "http://example.org/"
languageCode = "en-us"
title = "Jeril Sebastian"
theme = "yinyang"
googleAnalytics = "UA-96088457-2"

[params]
    headTitle = "Jeril Sebastian"
    mainSections = ["posts"]
    disqus = "jeril-xyz"

    [[params.socials]]
        name = "Github"
        link = "https://github.com/jerilseb"
        icon = "images/github.png"

    [[params.socials]]
        name = "LinkedIn"
        link = "https://www.linkedin.com/in/jer46/"
        icon = "images/linkedin.png"


    [[params.socials]]
        name = "StackOverflow"
        link = "https://stackoverflow.com/users/2219671/jeril-sebastian"
        icon = "images/stackoverflow.png"

[markup]
    [markup.highlight]
        codeFences = true
        guessSyntax = false
        hl_Lines = ""
        lineNoStart = 1
        lineNos = false
        lineNumbersInTable = true
        noClasses = true
        # style = "solarized-dark"
        # style = "perldoc"
        # style = "tango"
        # style = "native"
        style = "dracula"
        tabWidth = 4

    [markup.goldmark.renderer]
        unsafe= true