#!/usr/bin/env bash
echo -e "Removing public/"
rm -rf public/

echo -e "Building the site.."
docker container run --rm \
    -v $(pwd):/app \
    -w /app \
    -u $(id -u ${USER}):$(id -g ${USER}) \
    klakegg/hugo:0.82.0-ubuntu build

cp -a quick-files/. public/

read -t 60 -p "Do you want to deploy to production? (y/N) "
echo    # Move to new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
    now --prod public/
else
    now public/
fi
