#!/usr/bin/env bash

echo -e "Building the site.."
docker build . -t myblog_deploy
docker run --rm -v $(pwd):/app myblog_deploy build

read -t 60 -p "Do you want to deploy to production? (y/N) "
echo    # Move to new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
    now --prod public/
else
    now public/
fi
